// vue-ui/src/views/HomeView.vue
<template>
  <div class="p-5 mb-4 bg-light text-dark rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Django &times; Vue</h1>
      <div class="col-xl-8 fs-4 my-3 py-2">
        DjClient is a full-stack web application built with Django and Vue. It
        uses the Django REST Framework to provide a RESTful API for the
        frontend, which is built with Vue and TypeScript.
        <hr />
        Includes a simple authentication system, with user registration, login,
        and logout.
      </div>
      <router-link
        class="btn btn-primary btn-lg"
        :to="{ name: 'signup' }"
        v-if="!authStore.isAuthenticated"
      >
        Get Started &rarr;
      </router-link>
      <button v-else disabled class="btn btn-outline-primary btn-lg">
        Logged in as <b>{{ authStore.username }}</b>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { RouterLink } from "vue-router";
import useAuthStore from "@/stores/auth";

const authStore = useAuthStore();
</script>

// react-ui/src/views/HomeView.tsx
import { Link } from "react-router-dom";

import {
  useUsername,
  useIsAuthenticated,
} from "@/services/store/slices/auth/hooks";

export default function HomeView() {
  const username = useUsername();
  const isAuthenticated = useIsAuthenticated();

  return (
    <div className="p-5 mb-4 bg-light text-dark rounded-3">
      <div className="container-fluid py-5">
        <h1 className="display-5 fw-bold">Django &times; React</h1>
        <div className="col-xl-8 fs-4 my-3 py-2">
          DjClient is a full-stack web application built with Django and React.
          It uses the Django REST Framework to provide a RESTful API for the
          frontend, which is built with React and TypeScript.
          <hr />
          Includes a simple authentication system, with user registration,
          login, and logout.
        </div>
        {!isAuthenticated ? (
          <Link to="/signup" className="btn btn-primary btn-lg">
            Get Started &rarr;
          </Link>
        ) : (
          <button className="btn btn-outline-primary btn-lg" disabled>
            Logged in as <b>{username}</b>
          </button>
        )}
      </div>
    </div>
  );
}
