// vue-ui/src/views/LoginView.vue
<template>
  <div class="row">
    <div class="col-lg-12 col-xl-6 offset-xl-3">
      <div class="card">
        <div class="card-title">
          <div class="card-body">
            <h1 class="card-title">Sign In</h1>
            <hr />
            <form @submit.prevent="handleSubmit">
              <div class="mb-3">
                <BSInput
                  auto-focus
                  id="username"
                  label="Username"
                  :value="credentials.username"
                  v-model="credentials.username.value"
                />
              </div>
              <div class="mb-3">
                <BSInput
                  id="password"
                  type="password"
                  label="Password"
                  :value="credentials.password"
                  v-model="credentials.password.value"
                />
              </div>
              <div class="d-grid">
                <button type="submit" class="btn btn-primary btn-lg">
                  Sign In
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive } from "vue";
import { useRouter } from "vue-router";

import useAuthStore from "@/stores/auth";
import useAlertStore from "@/stores/alert";
import BSInput from "@/components/BSInput.vue";
import { fetchLoginResponse } from "@/api/auth";
import type { Credentials } from "@/api/types/auth";

const router = useRouter();
const authStore = useAuthStore();
const alertStore = useAlertStore();

const credentials = reactive<Credentials>({
  username: { value: "", errors: [] },
  password: { value: "", errors: [] },
});

const handleSubmit = async () => {
  alertStore.clearMessages();
  try {
    const response = await fetchLoginResponse(credentials);
    authStore.login(response);
    await router.push({ name: "home" });
  } catch (e: any) {
    alertStore.addDangerMessage(e.message);
  }
};
</script>

// react-ui/src/views/LoginView.tsx
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { useState, useEffect, FormEvent, ChangeEvent } from "react";

import BSInput from "@/components/BSInput";
import { Credentials } from "@/services/api/types/auth";
import { fetchLoginResponse } from "@/services/api/auth";
import { login } from "@/services/store/slices/auth/authSlice";
import { useIsAuthenticated } from "@/services/store/slices/auth/hooks";
import { addAlert, AlertType } from "@/services/store/slices/alert/alertSlice";

export default function LoginView() {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const isAuthenticated = useIsAuthenticated();
  const [credentials, setCredentials] = useState<Credentials>({
    username: { value: "", errors: [] },
    password: { value: "", errors: [] },
  });

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/");
    }
  }, []);

  const generateInputHandler =
    (key: keyof Credentials) => (e: ChangeEvent<HTMLInputElement>) => {
      setCredentials({
        ...credentials,
        [key]: { value: e.target.value, errors: [] },
      });
    };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      const response = await fetchLoginResponse(credentials);
      dispatch(login(response));
      navigate("/");
    } catch (e: any) {
      dispatch(addAlert({ message: e.message, type: AlertType.Danger }));
    }
  };

  return (
    <div className="row">
      <div className="col-lg-12 col-xl-6 offset-xl-3">
        <div className="card">
          <div className="card-body">
            <h1 className="card-title">Sign In</h1>
            <hr />
            <form onSubmit={handleSubmit}>
              <div className="mb-3">
                <BSInput
                  autoFocus
                  id="username"
                  label="Username"
                  value={credentials.username}
                  onChange={generateInputHandler("username")}
                />
              </div>
              <div className="mb-3">
                <BSInput
                  id="password"
                  label="Password"
                  value={credentials.password}
                  onChange={generateInputHandler("password")}
                />
              </div>
              <div className="d-grid">
                <button type="submit" className="btn btn-primary btn-lg">
                  Sign In
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
